config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#index'
  get '/users/edit' => 'users#edit', :as => :edit_user
  resources :users, :photos, :galleries, :sessions, :pages

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/signup' => 'users#new'
  # post '/edit' => 'users#edit'
  # Do not include the above line, but leave it here to remember what you did.
  post '/users' => 'users#create'


end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  name       :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Gallery < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  name       :text
#  image      :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tags       :text
#

class Photo < ActiveRecord::Base
	belongs_to :user 
	has_many :galleries
end	

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  created_at      :datetime
#  updated_at      :datetime
#  hometown        :text
#  image           :text
#  bio             :text
#  password_digest :text
#

class User < ActiveRecord::Base
	has_secure_password
	has_many :photos

	validates :email, :presence => true, :uniqueness => true 
  	validates :name, :presence => true, :uniqueness => true, :length => { :minimum =>3 }
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exceptions

  before_action :fetch_current_user

  private
  def fetch_current_user
  	if session[:user_id].present?
  		@current_user = User.find_by :id => session[:user_id]
  		session[:user_id] = nil unless @current_user.present?
  	end	
  end	
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	def index
    @galleries = Gallery.all #this uses active record to writ sql to get all authors
  end

  def show
    @gallery = Gallery.find params[:id]
  end

  def edit
    @gallery = Gallery.find params[:id]
  end

  def update
    @gallery = Gallery.find params[:id]
    @gallery.update gallery_params
    redirect_to gallery_path
  end

  def new
    @gallery = Gallery.new
  end

  def create
    gallery = Gallery.new gallery_params
    if gallery.save
      redirect_to galleries_path 
    else
      redirect_to new_gallery_path
    end
  end

  def destroy
    gallery = Gallery.find params[:id]
    gallery.destroy
    redirect_to galleries_path
  end

  private
  def gallery_params
    params.require(:gallery).permit(:name)
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photo = Photo.all
  end

  def show
    @photo = Photo.find params[:id]
  end

  def edit
    @photo = Photo.find params[:id]
  end

  def update
    @photo = Photo.find params[:id]
    @photo.update photo_params
    redirect_to photo_path
  end 

  def new
    @photo = Photo.new
  end

  def create 
    response = Cloudinary::Uploader.upload params[:file]
    @photo = Photo.create name: params[:name], image: response["url"]
      if @current_user.photos << @photo
      end
      unless (Gallery.find params[:gallery_id]).nil?
        (Gallery.find params[:gallery_id]).photos << @photo
      end
      redirect_to galleries_path
   end 

  def destroy
    photo = Photo.find params[:id]
    photo.destroy
    redirect_to photos_path
  end

  private
  def photo_params
    params.require(:photo).permit(:name, :user_id, :file, :image, :url)
  end 

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
  	user = User.find_by :email => params[:email]
  	if user.present? && user.authenticate(params[:password])
  		session[:user_id] = user.id 
  		redirect_to root_path
  	else
  		redirect_to login_path	
  	end	
  end

  def destroy 
  	session[:user_id] = nil
  	redirect_to root_path
  end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all 
  end

  def show
    @user = User.find params[:id]
  end

  def edit
 	
  end

  def update
    @user = User.find params[:id]
    @user.update user_params
    redirect_to user_path
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to '/'
      else
      redirect_to '/signup'
      end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path
  end

  def photos
    @user = User.find params[:user_id]
    @photo = Photo.new
  end

  private
  def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation, :hometown, :image, :bio)
  end 

   def check_if_logged_in
  	redirect_to root_path unless @current_user.present?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <%= f.submit "Create Gallery" %>
<% end %>

app/views/galleries/edit.html.erb
<h1>Edit Gallery</h1>

<%= render :partial => 'form' %>

app/views/galleries/index.html.erb
<h1>Galleries Index</h1>

<% @galleries.each do |gallery| %>
	<p> <%= link_to( gallery.name, gallery ) %></p> 
<% end %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<h2> <%= @gallery.name %> </h2>

<%= image_tag @gallery.image %>
	
<% @gallery.photos.each do |photo| %>
	<%= link_to(image_tag(photo.image), photo) %>
<% end %>

<%= link_to 'Back', galleries_path %>
<%= link_to 'Delete',  @user, :method => 'delete', :data => { :confirm => "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FOCUS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
<nav>
  <div class="unlogged">
  <% if @current_user.present? %>
    <%= link_to "Logout #{ @current_user.name}", login_path, :method => 'delete', :data => { :confirm => 'Are you sure you wish to logout?' } %>
    <%= link_to 'Home', '/' %>
    <%= link_to 'Browse Photos', photos_path %>
    <%= link_to 'Add A New Photo', new_photo_path %>
    <%= link_to 'Browse Galleries', galleries_path %>
    <%= link_to 'Create Gallery', new_gallery_path %>
    <%= link_to 'Browse Users', users_path %>
    <%= link_to 'Edit Profile', edit_user_path(@current_user) %>
  </div>
  <% else %>
    <div class="unlogged">
      <%= link_to 'Sign Up', new_user_path %>
      <%= link_to 'Login', login_path %>
    </div>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>FOCUS app</h1>

<h2>What is this all about?</h2>
<p>This is designed for anyone who is looking to find creative inspiration without the noise and distraction of social-media that most photos sharing websites incporporate these days.</p>

<h2>But why would we want to be part of a community with no social sharing love?</h2>
<p>Sometimes you just need to remove all of the distractions.</p>

app/views/pages/show.html.erb
<h2>Where stuff has to go.....</h2>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<h1>Photos Index</h1>

<% @photo.each do |photo| %>
  <%= link_to ( image_tag photo.image ), photo_path(photo.id) %>
<% end %>

app/views/photos/new.html.erb
<h1>Upload A New Photo</h1>

<%= form_tag "/photos", multipart: true do %>
  <p>
    <%= label_tag "Photo Name: " %>
    <%= text_field_tag :name %>
  </p>

  <p>
    <%= label_tag "Photo Image: " %>
    <%= cl_image_upload_tag :file %>
  </p>	

  <p>
     <%= label_tag "Galleries: " %>
     <%= select_tag :gallery_id, options_for_select(Gallery.all.map { |gallery| [ gallery.name, gallery.id ] }),
		:include_blank => true %> 
  </p>


  	<%= submit_tag "Add Photo" %>


<% end %>


<h2>Creative Commons Licenses</h2>

<article>
<h3>What is a CC licence?</h3>

<p>The CC licences provide a simple standardised way for individual creators, companies and institutions to share their work with others on flexible terms without infringing copyright. The licences allow users to reuse, remix and share the content legally.</p>
<p>Offering your work under a Creative Commons licence does not mean giving up your copyright. It means permitting users to make use of your material in various ways, but only on certain conditions.</p>


<h3>Attribution BY</h3>
<p>This applies to every Creative Commons work. Whenever a work is copied or redistributed under a Creative Commons licence, the original creator (and any other nominated parties) must be credited and the source linked to.</p>


<h3>NonCommercial NC</h3>
<p>This applies to every Creative Commons work. Whenever a work is copied or redistributed under a Creative Commons licence, the original creator (and any other nominated parties) must be credited and the source linked to.	Lets others copy, distribute, display and perform the work for noncommercial purposes only.</p>


<h3>No Derivative Works ND</h3>
<p>Lets others distribute, display and perform only verbatim copies of the work. They may not adapt or change the work in any way.
</p>


<h3>Share Alike SA</h3>
<p>Allows others to remix, adapt and build on the work, but only if they distribute the derivative works under the same the licence terms that govern the original work.
</p>

<a href="http://creativecommons.org.au/learn/licences/">Source</a>
</article>

app/views/photos/show.html.erb
<h2> <%= @photo.name %> </h2>

<ul>
	<div class="tilt pic">
    <p><%= image_tag @photo.image %> </p>
	</div>
    	<% if @photo.user %>
  			<p>Photographer
	    	<a href="/users/<%= @photo.user.id %>">
	      	<%= @photo.user.name %>
	    	</a>
		<% end %>
</ul>

<p><%= link_to 'Back', photos_path %></p>

<% if @photo.user == @current_user %>
<%= link_to'Edit', edit_photo_path(@photo) %> 
<%= link_to 'Delete',  @photo, :method => 'delete', :data => { :confirm => "Are you sure?" } %>
<% end %>

app/views/session/new.html.erb
<h1>Login</h1>

<div class="login">
	<%= form_tag '/login' do %>
	  <p> Email: <%= text_field_tag :email %> </p>
	  <p> Password: <%= password_field_tag :password %> </p>
	  <p> <%= submit_tag "Submit" %> </p>		
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @current_user do |f| %>

<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :email %>
    <%= f.text_field :email %>
</p>    

<p>
    <%= f.label :hometown %>
    <%= f.text_field :hometown %>
</p>    

<p>
    <%= f.label :image %>
    <%= f.url_field :image %>
</p>    

<p>
    <%= f.label :bio %>
    <%= f.text_area :bio  %>
</p>    

    <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1>Users Index</h1>

<% @user.each do |user| %>
	<p> <%= link_to( user.name, user ) %></p> 
<% end %>

app/views/users/new.html.erb
<h1>New Users</h1>

<h2>Create an account...</h2>

<%= form_for :user, url: '/users' do |f| %> 
  Email: <%= f.text_field :email, placeholder: "email address", :autofocus => true %>
  Name: <%= f.text_field :name, placeholder: "name"  %>
  Password: <%= f.password_field :password, placeholder: "password" %>
  Password Confirmation: <%= f.password_field :password_confirmation, placeholder: "password" %>
<%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h2> <%= @user.name %> </h2>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Hometown:</strong>
  <%= @user.hometown %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>


<% @user.photos.each do |user| %>
	<%= link_to(image_tag(user.image, :class => 'thumb'), user) %>
<% end %>
  <p>
  <%= link_to 'Back', users_path %>
    <% if @user == @current_user %>
      <%= link_to'Edit', edit_user_path(@user_id) %> 
      <%= link_to 'Delete',  @user, :method => 'delete', :data => { :confirm => "Are you sure?" } %>
    <% end %>
</p>